on:
  push:
    branches:
      - master
  pull_request:


jobs:
  call-test-workflow:
    uses: wvangeit/osparc-meta-parallelrunner/.github/workflows/test.yml@master
    newversion:
      name: make new version
      runs-on: ubuntu-latest
      needs:
          call-test-workflow
      permissions:
          contents: write
      steps:
        - uses: actions/checkout@v4
          with:
              fetch-depth: 0
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
              python-version: 3.11
        # - name: Install dependencies
        #   run: python -m pip install --upgrade pip setuptools build
        - name: Make new version
          run:
            make version-path
